{% set python_min = "3.10.0" %}
{% set name = "zarrtraj" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/zarrtraj-{{ version }}.tar.gz
  sha256: 9c4724cca0dc12d384a885b39198e74410be34a618ace79012e46ccfa864d854

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - mdanalysis >=2.7.0
    - zarr >=2.11.0
    - kerchunk >=0.2.6
    - h5py >=3.11.0
    - s3fs >=2024.3.0
    - gcsfs >=2024.6.1
    - adlfs >=2024.7.0

test:
  imports:
    - zarrtraj
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Becksteinlab/zarrtraj
  summary: Zarrtraj is a kit that provides the ability to stream & analyze H5MD trajectories from cloud storage.
  license: GPL-3.0-or-later
  license_file: LICENSE
  description: |
    Zarrtraj is an MDAnalysis MDAKit that provides the ability to read and write H5MD-formatted trajectory data in MDAnalysis using Zarr. 
    Zarrtraj can read trajectories locally and from AWS S3, Google Cloud Buckets, and Azure Blob Storage & DataLakes.
    It can read both H5MD-formatted files stored in hdf5 (.h5md files) and H5MD-formatted files stored in Zarr (.zarrmd files).
  doc_url: https://zarrtraj.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/Becksteinlab/zarrtraj

extra:
  recipe-maintainers:
    - ljwoods2
    - hmacdope
